<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>prog1</groupId>
    <artifactId>sortdemo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <repositories>
        <repository>
            <id>project-repo</id>
            <url>file://${project.basedir}/repo</url>
        </repository>
    </repositories>
    <build>
        <plugins>
           <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>Application</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>ch.fhnw.algd</groupId>
            <artifactId>algorithms.algd</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ch.fhnw.algd</groupId>
            <artifactId>awt.numericalview</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ch.fhnw.algd</groupId>
            <artifactId>awt.simpleview</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ch.fhnw.algd</groupId>
            <artifactId>awt.window</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ch.fhnw.algd</groupId>
            <artifactId>framework</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>ch.fhnw.algd</groupId>
            <artifactId>viewPicker</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
</project>